### ISSUE TITLE
Installer stuck waiting for Ansible

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#26]
## Expression of Error
Infrastructure successfully provisions, but the installer goes into an infinite loop waiting for Ansible to be ready (_to execute the Ansible scripts_).

## Version Affected
Encountered on `v1.1`. Likely affects earlier versions.

## Cause of Error
If you SSH onto the created instance and check the Launch Template log at `/var/log/tower-forge.log`, you will see this error at the bottom:
 
```bash
curl: (28) Failed to connect to bootstrap.pypa.io port 443 after 132513 ms: Couldn't connect to server
python3: can't open file '/home/ec2-user/get-pip.py': [Errno 2] No such file or directory
/usr/bin/python3: No module named pip
/root/tower-forge.sh: line 15: ansible: command not found

rm: cannot remove 'get-pip.py': No such file or directory
```

The Launch Template installs Ansible via `pip`. The failure to install `pip` means Ansible cannot be installed which means we can never satisfy the exit criteria of the infinite 'wait for Ansible to be ready' loop.

### Workarounds and Remaining Errors
Running the following commands on the instance will result in Ansible being installed:
```bash
cd /home/ec2-user
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```

Unfortunately, this does not seem to cause the infinite loop to break. You must `ctrl+C` the Terraform deployment and run it again via `terraform apply`. This will allow Ansible installation to start.

Another error is thrown at the `pyyaml` installation step - TBD what is causing this:
```bash
│ TASK [Install pyyaml (needed by seqerakit)] ************************************
│ fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find any of pip3 to use.  pip needs to be installed."}
```

**Comment by gwright99** [comment]
## Update:
Deleting the EC2 instance within AWS and rerunning `terraform apply` (after uncommenting the `overwrite` flags in `005_parameter_store.tf`) resulted in a successful e2e flow.

### Mitigation Approach
Discussion ongoing with team stakeholders re: best approach to make this part of the process more defensive:
- I favour a loop in the Launch Template (similar to the loop used to check for Ansible) that will look for the presence of `get-pip.py` before continuing.
- A `sleep` command at the start of the LT may introduce enough of a lag to compensate for any race condition re: the EC2 trying to download a file before it has the necessary connectivity. 
- Other?

**Comment by adriannavarrobetrian** [comment]
Running both commands with && in one line:

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py`

should work, the second command will only run when the file is downloaded.

**Comment by adriannavarrobetrian** [comment]
Wrong assumption. This actually fixes the issue:

`      # Wait until the get-pip.py file is available
      while [ ! -f get-pip.py ]
      do
        sleep 1
      done
`

**Comment by gwright99** [comment]
@adriannavarrobetrian this is the snippet I was using for my patch attempt.

```bash
      timeout 15s bash -c \
        'until [ -f //home/ec2-user/get-pip.py ]; do 
          echo "Trying to curl get-pip.py"
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          sleep 1
        done'
```

Logic: I don't want the machine getting stuck in an infinite startup loop because that'll make diagnosing more difficult to diagnose if we cant jump onto the box (**note:** since the AMI should already have SSH running, I'm not sure if an infinite loop in the LT would preclude one being able to SSH onto the node at the same time).

With that said, I'd personally rather allow the LT to fail-through and get everything else done -- we'll know something is wrong anyways due to the subsequent "Waiting for Ansible" loop.

Alternatively, we could consider loading up the CloudWatch agent at the start (like we do with TowerForge-created AWS Batch CEs) before the pip logic -- this would allow us to emit some status messages to a CloudWatch-accessible log.

Thoughts?

**Comment by adriannavarrobetrian** [comment]
@gwright99 We can do something like this:

`counter=0
while [ ! -f get-pip.py ] && [ $counter -lt 10 ]; do 
  echo "File not found, retrying download..."
  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  sleep 1
  counter=$((counter+1))
done

if [ $counter -eq 10 ]; then
  echo "Failed to download file after 10 attempts."
fi`

**Comment by gwright99** [comment]
I'm ok with this. Do you want to put together the PR for your first contribution to the project?
