### ISSUE TITLE
Fix typo on nginx configuration

### ISSUE THREAD

**Issue by markpanganiban** [seqeralabs/cx-field-tools-installer#32]
https://github.com/seqeralabs/cx-field-tools-installer/blob/master/assets/src/customcerts/custom_default.conf#L34-L35

```
        proxy_set_header        X-Forwarded_For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded_Proto $scheme;
```

When debugging the Entra OIDC issue, I found this typo and wondered why the forwarding doesn't work. I believe the values should be:

```
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
```

This affects folks who are trying to use the reverse proxy container and trying to integrate with their OIDC, mainly for Azure Entra ID. The authorization requests that will flow to the OIDC provider will not contain the critical header requirement for Azure.

**Comment by gwright99** [comment]
Rad. Asked for you to include a bit of test documentation in the PR (please), then I'll merge.
