### ISSUE TITLE
[ Enhancement ] - Implement pure Seqerakit CodeCommit credentials

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#83]
Due to limitations in [tower-cli v0.9.1](https://github.com/seqeralabs/tower-cli), a kludgy workaround was implemented to support CodeCommit credentials [see https://github.com/seqeralabs/cx-field-tools-installer/issues/20](https://github.com/seqeralabs/cx-field-tools-installer/issues/20).

Current as of June 13/24, the tower-cli team have an [open PR to natively support CodeCommit credentials](https://github.com/seqeralabs/tower-cli/pull/420). The project should be updated once this merged to master and released:

## To Do
- [x] Update tw version in Ansible script
- [x] Remove branching Seqerakit path in Ansible script
- [x] Retain implementation pattern in project documentation so that it can be reused for other not-yet-natively-supported Seqera Platform objects.

**Comment by gwright99** [comment]
@schaluva has kindly volunteered to tackle this as her first contribution to the project -- thank you! :)

**Comment by JaimeSeqLabs** [comment]
@gwright99, @schaluva CodeCommit credentials support just landed in [v0.9.3 release](https://github.com/seqeralabs/tower-cli/releases/tag/v0.9.3)
