### ISSUE TITLE
[ 24.1 Release Task ] Update db connection string logic

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#84]
As per Seqera Engineering and Documentation resources, Tower v24.1.0 is requires the addition of a new database connection string modifier ([internal source](https://github.com/seqeralabs/platform/pull/6584)). The actual value is dependent on the `mysql` version:

- mysql 5.6
    `TOWER_DB_URL=jdbc:[mysql://db:3306/tower?permitMysqlScheme=true&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'`

- mysql 5.7+
    `TOWER_DB_URL=jdbc:[mysql://db:3306/tower?permitMysqlScheme=true`

## Tasks
- [ ] Add additional logic to [`tower.env.tpl`](https://github.com/seqeralabs/cx-field-tools-installer/blob/master/assets/src/tower_config/tower.env.tpl#L22-L27) db settings.
- [ ] Add python validation logic forbidding MySQL 5.6

**Comment by gwright99** [comment]
@swampie -- I think I got the connection string logic requirements right but could you please verify?

**Comment by swampie** [comment]
approved!!!
